# permissions for end users to view awsbackends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: awsbackend-viewer-role
rules:
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - awsbackends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - awsbackends/status
  verbs:
  - get
