# permissions for end users to view backends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-viewer-role
rules:
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - backends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - backends/status
  verbs:
  - get
