
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - awsbackends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - awsbackends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - externalbackends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - externalbackends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loadbalancer.takutakahashi.dev
  resources:
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
