apiVersion: loadbalancer.takutakahashi.dev/v1beta1
kind: AWSBackend
metadata:
  name: aws-nlb-sample
spec:
  target: {}
  livenessProbe: {}
  readinessProbe: {}
status:
  globalIP: 12.34.56.7

---
apiVersion: loadbalancer.takutakahashi.dev/v1beta1
kind: ExternalBackend
metadata:
  name: external-sample
spec:
  globalIP: 12.34.56.8
  livenessProbe: {}
  readinessProbe: {}
status:
  globalIP: 12.34.56.8
