apiVersion: loadbalancer.takutakahashi.dev/v1beta1
kind: AWSBackend
metadata:
  name: awsbackend-sample
spec:
  credentials:
   accessKeyID:
     secretKeyRef:
       name: aws-credentials
       key: aws_access_key_id
   secretAccessKey:
     secretKeyRef:
       name: aws-credentials
       key: aws_secret_access_key
  region: ap-northeast-1
  type: network
  vpc:
    id: vpc-082f7dcbe447d7ba7
  subnets:
    - id: subnet-04ddc1d62069e344c
  listeners:
    - port: 443
      protocol: TCP
      defaultAction:
        type: forward
        targetGroup:
          port: 443
          protocol: TCP
          targetType: ip
          targets:
            - destination:
                IP: 10.0.0.11
              port: 443
